### PR TITLE
Fix typos and markdowns

### PR DESCRIPTION
**Pull request by kianmeng**
See a detailed description of the rules is available at
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

### CODE REVIEW

**Review by Kaesebrot84 — APPROVED** [review]
@kianmeng Thank you very much for your contribution!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Comment by kianmeng** [comment]
@Kaesebrot84 By the way, how did you generate this image, https://raw.githubusercontent.com/Kaesebrot84/iris/main/example_output.png?

**Comment by Kaesebrot84** [comment]
> @Kaesebrot84 By the way, how did you generate this image, https://raw.githubusercontent.com/Kaesebrot84/iris/main/example_output.png?

I did it by running `cliris -f Lenna.png -i 3 html` which generates a html file. Then I took a screenshot of the html file content.

**Pull request merged**
